[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""
radio = "ft950"

[input-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 1

[output-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 2

[opus]
application = "restricted_lowdelay"
bitrate = 24000
complexity = 5
max-bandwidth = "wideband"

[audio]
codec = "opus"
rx-buffer-length = 10
# opus does not accept arbitrary frame length! Check OPUS documentation
frame-length = 960  #20ms @ 48kHz (should work for most cases)
tx-volume = 70
rx-volume = 70
tx-on-startup = true

[http]
host = "localhost"
port = 9090