
[mqtt]
#broker-url = "localhost"
broker-url = "test.mosquitto.org"
broker-port = 1883
username = ""
password = ""
radio = "ft950"

[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""
radio = "ft950"

[input-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 1

[output-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 2

[pcm]
samplerate = 16000
bitdepth = 16
channels = 1

[opus]
application = "restricted_lowdelay"
bitrate = 32000
complexity = 9
max-bandwidth = "wideband"

[audio]
codec = "opus"
rx-buffer-length = 10
frame-length = 960  #20ms @ 48kHz (should work for most cases)
# opus does not accept arbitrary frame length! Check OPUS documentation

[webui]
disabled = false
address = "localhost"
port = 7070