language: go

dist: trusty
sudo: false
env:
    - GOARCH=amd64
    
go:
    - 1.6
    - 1.7
    - tip

addons:
    apt: 
      packages: 
         - pkg-config
         - libsamplerate0
         - libsamplerate0-dev
         - libopusfile-dev
         - libopus-dev
         - libportaudio2
         - portaudio19-dev
